config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'courses#index'
  resources :courses, only: [:index, :show], param: :slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = CareerFoundry::APIClient.get_all_courses
  end

  def show
    country_code = Geolocation.get_country_code
    @course_detail = CareerFoundry::APIClient.get_course_by_slug_and_location(params[:slug], country_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<div class="container mt-1">
  <h4>Pick course:</h4>
    <% @courses["courses"].each do |slug, course| %>
    <p>
      <a href="<%=course_path(slug)%>">
        <%=course["title"] %>
      </a>
    </p>
    <% end %>
</div>

app/views/courses/show.html.erb
<div class="container mt-1">
  <p>
    <a href="<%=courses_path%>">
      &larr;
    </a>
  </p>
  <h4>Course:</h4>
  <p>Price: <%=@course_detail["price"]["total"]%></p>
  <p>Next start date: <%=@course_detail["start_dates"].first %></p>
  <p>Following dates:</p>
  <ul>
    <li><%=@course_detail["start_dates"][1] %></li>
    <li><%=@course_detail["start_dates"][2] %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareerfoundryChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>